In [1]:
import tensorflow as tf

In [2]:
tf.__version__

&#39;1.14.0&#39;

In [3]:
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [4]:
sess

&lt;tensorflow.python.client.session.Session at 0x231794e5c08&gt;

In [5]:
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)

with tf.Session() as sess:
    print (sess.run(c))

[[22. 28.]
 [49. 64.]]


In [6]:
with tf.Session() as sess:
  devices = sess.list_devices()
devices

In [8]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: &quot;/device:CPU:0&quot;
device_type: &quot;CPU&quot;
memory_limit: 268435456
locality {
}
incarnation: 16095579395700543135
, name: &quot;/device:GPU:0&quot;
device_type: &quot;GPU&quot;
memory_limit: 6620742943
locality {
  bus_id: 1
  links {
  }
}
incarnation: 13759873787467052866
physical_device_desc: &quot;device: 0, name: GeForce RTX 2070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5&quot;
]


In [9]:
assert tf.test.is_gpu_available()
assert tf.test.is_built_with_cuda()

In [11]:
print(tf.test.is_built_with_cuda())

True


In [20]:
# import tensorflow_probability as tfp

a = tf.constant([[1.,  0.4,  0.5],
                 [0.4, 0.2,  0.25],
                 [0.5, 0.25, 0.35]])
import numpy as np
a= np.array(a)
b= np.linalg.pinv(a)
print(a)
print(b)

TypeError: loop of ufunc does not support argument 0 of type Tensor which has no callable conjugate method

In [21]:
bert_embedding=np.load("D:\CodeRepo\Thesis\Thesis\BERT\embeddings.npz")
y_df=np.load("D:\CodeRepo\Thesis\Thesis\EDA\Y.npz")

In [24]:
bert_embedding["t1"]

array([[-0.23652047, -0.46730292,  0.62800884, ..., -0.3478354 ,
         0.17314139, -0.6017166 ],
       [ 0.2007698 , -0.9118703 ,  0.74586886, ..., -0.7119921 ,
         0.29034543, -0.35151947],
       [-0.54077786,  0.09937867,  0.61585516, ..., -0.38611546,
         0.10635425, -0.26011148],
       ...,
       [-0.23731072, -0.38172564,  0.07030658, ...,  0.16959587,
         0.52745634, -1.0168482 ],
       [-0.3484214 , -0.721707  ,  0.16562451, ..., -0.51939166,
         0.4619452 , -0.33824992],
       [-0.44174305, -0.1110604 , -0.01783825, ..., -0.34670058,
         0.34106705, -0.15129046]], dtype=float32)

In [ ]:
def get_partition_Embeddings(x,y,df,partition_nm):
    _df=df[df["split"]=partition_nm]
    index_list=list(_df.index)
    temp_array_x=[]
    temp_array_y=[]
    for index in index_list:
        temp_array_x.append(x[index,:])
        temp_array_y.append(y[index,:])
    temp_array_x=np.array(temp_array_x)
    temp_array_y=np.array(temp_array_y)
    return temp_array_x, temp_array_y






In [56]:
bert_embedding["t1"][0,:]
rows=[1,2,3,6,9,10,34,67,89]
test_array=[]
for x in rows:
    test_array.append(bert_embedding["t1"][x,:])
    print(bert_embedding["t1"][x,:10])
test_array=np.array(test_array)
print(test_array)
print(test_array.shape)




[ 0.2007698  -0.9118703   0.74586886 -0.8697525  -0.57226115 -0.24949355
 -0.04359428 -0.17300647  1.0280551   0.33911157]
[-0.54077786  0.09937867  0.61585516 -0.631934   -0.55172604  0.0163905
 -0.522085   -0.47525892  0.859443   -0.25996763]
[-0.4701435  -0.18448775 -0.00838217 -0.9471479  -0.27859327 -0.7233698
 -0.2403428  -0.6327968   0.8770632   0.26553336]
[-5.5013138e-01 -8.5874611e-01  3.0033991e-02 -5.6631851e-01
 -5.5838817e-01 -6.2689040e-04 -3.1155422e-01 -3.2103887e-01
  5.6258190e-01  1.1212194e+00]
[-0.30193123 -0.585884    0.6640047  -0.27994165 -0.27713826 -0.44309044
 -0.6207534  -0.35149023  0.7461389   0.33850378]
[-0.5745434  -0.6234135   0.1759385  -0.98341745 -0.03513606 -0.2809695
 -0.1693242  -0.28055024 -0.24569269  0.5604806 ]
[-0.0532444  -0.46782023  0.06806639 -0.23257655 -0.47505942 -0.5427201
 -0.45661578 -0.08468816  0.9627716   0.14629103]
[ 0.20652439 -0.17011566  0.24326749 -0.9179479  -0.15629724 -0.69250315
 -0.28887078 -0.05260727  1.0344032  -0

In [31]:
bert_embedding["t2"]

array([[-0.40418392, -0.47878775,  0.7580885 , ..., -0.47598928,
         0.10172412, -0.33533862],
       [ 0.2230832 , -0.48024565,  0.75589806, ..., -0.75046986,
         0.44050843, -0.9165367 ],
       [-0.70129013,  0.2842256 ,  0.7363471 , ..., -0.50889647,
         0.14786258, -0.09948996],
       ...,
       [-0.26456812, -0.44883907,  0.15373003, ..., -0.0242345 ,
         0.7692909 , -1.2379875 ],
       [-0.2578964 , -0.7907244 ,  0.48381078, ..., -0.5863774 ,
         0.67240703, -0.13996066],
       [-0.4584682 , -0.02483118, -0.0885824 , ..., -0.4353699 ,
         0.48302737, -0.12356079]], dtype=float32)

In [33]:
Y=y_df['arr_0']


(14828, 71)

In [35]:
print("X SHAPE:",bert_embedding["t1"].shape)
print("X SHAPE:",Y.shape)


X SHAPE: (14828, 768)
X SHAPE: (14828, 71)


In [36]:
 from sklearn.model_selection import train_test_split

X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(bert_embedding["t1"], Y, test_size=0.3, random_state=42)

In [37]:
print("X_train_1 SHAPE:",X_train_1.shape)
print("X_test_1 SHAPE:",X_test_1.shape)
print("X_test_1 SHAPE:",y_train_1.shape)
print("y_test_1 SHAPE:",y_test_1.shape)

X_train_1 SHAPE: (10379, 768)
X_test_1 SHAPE: (4449, 768)
X_test_1 SHAPE: (10379, 71)
y_test_1 SHAPE: (4449, 71)


In [38]:
#CREATING THE ELM
import h5py

def _mean_squared_error(y_true, y_pred):
    return 0.5 * np.mean((y_true - y_pred)**2)

def _mean_absolute_error(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

def _sigmoid(x):
    return 1. / (1. + np.exp(-x))

def _identity(x):
    return x

class ELM(object):
    def __init__(
        self, n_input_nodes, n_hidden_nodes, n_output_nodes,
        activation='sigmoid', loss='mean_squared_error', name=None,
        beta_init=None, alpha_init=None, bias_init=None):

        self.name = name
        self.__n_input_nodes = n_input_nodes
        self.__n_hidden_nodes = n_hidden_nodes
        self.__n_output_nodes = n_output_nodes

        # initialize weights and a bias
        if isinstance(beta_init, np.ndarray):
            if beta_init.shape != (self.__n_hidden_nodes, self.__n_output_nodes):
                raise ValueError(
                    'the shape of beta_init is expected to be (%d,%d).' % (self.__n_hidden_nodes, self.__n_output_nodes)
                )
            self.__beta = beta_init
        else:
            self.__beta = np.random.uniform(-1.,1.,size=(self.__n_hidden_nodes, self.__n_output_nodes))
        if isinstance(alpha_init, np.ndarray):
            if alpha_init.shape != (self.__n_input_nodes, self.__n_hidden_nodes):
                raise ValueError(
                    'the shape of alpha_init is expected to be (%d,%d).' % (self.__n_hidden_nodes, self.__n_output_nodes)
                )
            self.__alpha = alpha_init
        else:
            self.__alpha = np.random.uniform(-1.,1.,size=(self.__n_input_nodes, self.__n_hidden_nodes))
        if isinstance(bias_init, np.ndarray):
            if bias_init.shape != (self.__n_hidden_nodes,):
                raise ValueError(
                    'the shape of bias_init is expected to be (%d,).' % (self.__n_hidden_nodes,)
                )
            self.__bias = bias_init
        else:
            self.__bias = np.zeros(shape=(self.__n_hidden_nodes,))

        # set an activation function
        self.__activation = self.__get_activation_function(activation)

        # set a loss function
        self.__loss = self.__get_loss_function(loss)

    def __call__(self, x):
        h = self.__activation(x.dot(self.__alpha) + self.__bias)
        return h.dot(self.__beta)

    def predict(self, x):
        return list(self(x))

    def evaluate(self, x, t, metrics=['loss']):
        y_pred = self.predict(x)
        y_true = t
        y_pred_argmax = np.argmax(y_pred, axis=-1)
        y_true_argmax = np.argmax(y_true, axis=-1)
        ret = []
        for m in metrics:
            if m == 'loss':
                loss = self.__loss(y_true, y_pred)
                ret.append(loss)
            elif m == 'accuracy':
                acc = np.sum(y_pred_argmax == y_true_argmax) / len(t)
                ret.append(acc)
            elif m == 'uar':
                num_classes = len(t[0])
                uar = []
                for i in range(num_classes):
                    tp = np.sum((y_pred_argmax == i) & (y_true_argmax == i))
                    tp_fn = np.sum(y_true_argmax == i)
                    uar.append(tp / tp_fn)
                uar = np.mean(uar)
                ret.append(uar)
            else:
                raise ValueError(
                    'an unknown evaluation indicator \'%s\'.' % m
                )
        if len(ret) == 1:
            ret = ret[0]
        elif len(ret) == 0:
            ret = None
        return ret


    def fit(self, x, t):
        H = self.__activation(x.dot(self.__alpha) + self.__bias)

        # compute a pseudoinverse of H
        H_pinv = np.linalg.pinv(H)

        # update beta
        self.__beta = H_pinv.dot(t)

    def save(self, filepath):
        with h5py.File(filepath, 'w') as f:
            arc = f.create_dataset('architecture', data=np.array([self.__n_input_nodes, self.__n_hidden_nodes, self.__n_output_nodes]))
            arc.attrs['activation'] = self.__get_activation_name(self.__activation).encode('utf-8')
            arc.attrs['loss'] = self.__get_loss_name(self.__loss).encode('utf-8')
            arc.attrs['name'] = self.name.encode('utf-8')
            f.create_group('weights')
            f.create_dataset('weights/alpha', data=self.__alpha)
            f.create_dataset('weights/beta', data=self.__beta)
            f.create_dataset('weights/bias', data=self.__bias)

    def __get_activation_function(self, name):
        if name == 'sigmoid':
            return _sigmoid
        elif name == 'identity':
            return _identity
        else:
            raise ValueError(
                'an unknown activation function \'%s\'.' % name
            )

    def __get_activation_name(self, activation):
        if activation == _sigmoid:
            return 'sigmoid'
        elif activation == _identity:
            return 'identity'

    def __get_loss_function(self, name):
        if name == 'mean_squared_error':
            return _mean_squared_error
        elif name == 'mean_absolute_error':
            return _mean_absolute_error
        else:
            raise ValueError(
                'an unknown loss function \'%s\'.' % name
            )

    def __get_loss_name(self, loss):
        if loss == _mean_squared_error:
            return 'mean_squared_error'
        elif loss == _mean_absolute_error:
            return 'mean_absolute_error'
    
    @property
    def weights(self):
        return {
            'alpha': self.__alpha,
            'beta': self.__beta,
            'bias': self.__bias,
        }

    @property
    def input_shape(self):
        return (self.__n_input_nodes,)

    @property
    def output_shape(self):
        return (self.__n_output_nodes,)

    @property
    def n_input_nodes(self):
        return self.__n_input_nodes

    @property
    def n_hidden_nodes(self):
        return self.__n_hidden_nodes

    @property
    def n_output_nodes(self):
        return self.__n_output_nodes

    @property
    def activation(self):
        return self.__get_activation_name(self.__activation)

    @property
    def loss(self):
        return self.__get_loss_name(self.__loss)

def load_model(filepath):
    with h5py.File(filepath, 'r') as f:
        alpha_init = f['weights/alpha'][...]
        beta_init = f['weights/beta'][...]
        bias_init = f['weights/bias'][...]
        arc = f['architecture']
        n_input_nodes = arc[0]
        n_hidden_nodes = arc[1]
        n_output_nodes = arc[2]
        activation = arc.attrs['activation'].decode('utf-8')
        loss = arc.attrs['loss'].decode('utf-8')
        name = arc.attrs['name'].decode('utf-8')
        model = ELM(
            n_input_nodes=n_input_nodes,
            n_hidden_nodes=n_hidden_nodes,
            n_output_nodes=n_output_nodes,
            activation=activation,
            loss=loss,
            alpha_init=alpha_init,
            beta_init=beta_init,
            bias_init=bias_init,
            name=name,
        )
    return model

In [45]:
def softmax(x):
    c = np.max(x, axis=-1)
    upper = np.exp(x - c)
    lower = np.sum(upper, axis=-1)
    return upper / lower

model = ELM(
        n_input_nodes=768,
        n_hidden_nodes=5000,
        n_output_nodes=71,
        loss="mean_squared_error",
        activation="sigmoid",
        name='elm',
    )

In [46]:
model.fit(X_train_1,y_train_1)
train_loss, train_acc, train_uar = model.evaluate(X_train_1, y_train_1, metrics=['loss', 'accuracy', 'uar'])
print('train_loss: %f' % train_loss) # loss value
print('train_acc: %f' % train_acc) # accuracy
print('train_uar: %f' % train_uar) # uar (unweighted average recall)

train_loss: 0.008211
train_acc: 0.477599
train_uar: 0.450380


In [47]:
val_loss, val_acc, val_uar = model.evaluate(X_test_1, y_test_1, metrics=['loss', 'accuracy', 'uar'])
print('val_loss: %f' % val_loss)
print('val_acc: %f' % val_acc)
print('val_uar: %f' % val_uar)

val_loss: 0.046401
val_acc: 0.119802
val_uar: nan


In [48]:

    y_predicted = softmax(model.predict(X_test_1))

    for i in range(len(y)):
        print('---------- prediction %d ----------' % (i+1))
        class_pred = np.argmax(y_predicted[i])
        prob_pred = y_predicted[i][class_pred]
        class_true = np.argmax(y_test_1[i])
        print('prediction:')
        print('\tclass: %d, probability: %f' % (class_pred, prob_pred))
        print('\tclass (true): %d' % class_true)

ValueError: operands could not be broadcast together with shapes (4449,71) (4449,) 

In [ ]:
#sample input matrix format - true labels and predicted labels
#y_true = np.array([[1,0,1,1],[0,1,0,0],[0,0,0,0],[0,1,1,0]])
#y_pred = np.array([[0,0,1,1],[1,1,0,1],[0,1,0,0],[1,1,1,1]]

#function to calculate some comman values for all the metrics
def pre_cal(target, prediction, print_all = False):
    if(target.shape != prediction.shape):
        print("Wrong predictions matrics!")

    real_pos = real_neg = pred_pos = pred_neg  = true_pos = true_neg = []

    for i in range(y_true.shape[0]):
        # real values - RP and RN
        real_pos = np.asarray(np.append(real_pos,np.logical_and(y_true[i], y_true[i]).sum()), dtype=np.int64).reshape(-1,1)
        real_neg = np.asarray(np.append(real_neg,np.logical_and(np.logical_not(y_true[i]),np.logical_not(y_true[i])).sum()), dtype=np.int64).reshape(-1,1)

        # predicted values - PP and PN
        pred_pos = np.asarray(np.append(pred_pos,np.logical_and(y_pred[i], y_pred[i]).sum()),dtype=np.int64).reshape(-1,1)
        pred_neg = np.asarray(np.append(pred_neg,np.logical_and(np.logical_not(y_pred[i]), np.logical_not(y_pred[i])).sum()),dtype=np.int64).reshape(-1,1)

        # true labels - TP and TN
        true_pos = np.asarray(np.append(true_pos,np.logical_and(y_true[i], y_pred[i]).sum()),dtype=np.int64).reshape(-1,1)
        true_neg = np.asarray(np.append(true_neg,np.logical_and(np.logical_not(y_true[i]), np.logical_not(y_pred[i])).sum()),dtype=np.int64).reshape(-1,1)

    if print_all:
		# if print_all = True - it prints RP, RN, PP, PN, TP and TN
        result = np.concatenate((real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg), axis=1)
        print(result)

    return(real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg)

#function to resolve divide by zero error and accept the value 0 when divided by 0
def divideZero( value_a, value_b):
    with np.errstate(divide='ignore', invalid='ignore'):
        result = np.true_divide( value_a, value_b )
        result[ ~ np.isfinite( result )] = 0
    return result

def accuracy(target, predicted):
    #return the accuracy - example based
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)
    score = (true_pos + true_neg)/(pred_pos + pred_neg)
    score = np.mean(score)
    return score


def precision(target, predicted):
    #return precision - example based
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)
    score = divideZero(true_pos, pred_pos)
    score = np.mean(score)
    return score

def recall(target, predicted):
    #return precision - example based
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)
    score = divideZero(true_pos, real_pos)
    score = np.mean(score)
    return score


def fscore(target, predicted,beta = 1):
	#return f(beta)score - example based : default beta value is 1
    prec, rec = precision(y_true, y_pred), recall(y_true, y_pred)
    beta_val = beta*beta
    score = ((1+beta_val)*(prec*rec))/(beta_val*(prec+rec))
    return score


def hamloss(target, predicted):
	#return hamming loss - example based
    hamloss = list()
    for i in range(y_true.shape[0]):
        hamloss = np.asarray(np.append(hamloss,np.logical_xor(y_true[i], y_pred[i]).sum()), dtype=np.int64).reshape(-1,1)
    score = (hamloss.sum())/((y_true.shape[0])*(y_true.shape[1]))
    return score


def subset(target, predicted):
	#return subset accuracy - example based
    subset_matrix = list()
    for i in range(y_true.shape[0]):
        subset_matrix = np.asarray(np.append(subset_matrix, np.array_equal(y_true[i],y_pred[i])), dtype=np.int64).reshape(-1,1)
    score = (subset_matrix.sum())/((y_true.shape[0])*(y_true.shape[1]))
    return score

def zeroloss(target, predicted):
    #return new array with removed element having all zero in y_true
    condition = list()
    index = list()
    for i in range(y_true.shape[0]):
        new_true = new_pred = list()
        condition = np.logical_and(y_true[i],y_true[i]).sum()
        if (condition==0):
            index = np.asarray(np.append(index,i), dtype = np.int64)

        new_true = np.delete(y_true,index, axis = 0)
        new_pred = np.delete(y_pred,index, axis = 0)
    return new_true, new_pred

def microprecision(target, predicted):
    #return micro-precision
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)
    score = true_pos.sum()/pred_pos.sum()
    return score

def microrecall(target, prediction):
    #return micro-recall
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)
    score = true_pos.sum()/real_pos.sum()
    return score

def microfscore(target, predicted,beta = 1):
    #return micro-fscore
    prec, rec = microprecision(y_true, y_pred), microrecall(y_true, y_pred)
    beta_val = beta*beta
    score = ((1+beta_val)*(prec*rec))/(beta_val*(prec+rec))
    return score

def macroprecision(target, predicted):
    #return macro-precision
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)
    score = divideZero(true_pos, pred_pos)
    return score

def macrorecall(target, predicted):
    #return macro-recall
    real_pos, real_neg, pred_pos, pred_neg, true_pos, true_neg = pre_cal(y_true,y_pred)
    score = divideZero(true_pos, real_pos)
    return score

def macrofscore(target, predicted,beta = 1):
    #return macro-fscore
    prec, rec = macroprecision(y_true, y_pred), macrorecall(y_true, y_pred)
    beta_val = beta*beta
    score = divideZero(((1+beta_val)*(prec*rec)),(beta_val*(prec+rec)))
    score = np.mean(score)
    return score

In [73]:
mult_data=np.dot(np.array([[.3,.4,.5],[.2,.5,.4]]),np.transpose(np.array([[.6,.4,.7],[.4,.5,.6]])))
mult_data

array([[0.69, 0.62],
       [0.6 , 0.57]])

In [74]:
sigFunc=lambda x: 1. / (1. + np.exp(-x))

In [77]:
sigFunc(mult_data)

array([[0.66596693, 0.65021855],
       [0.64565631, 0.63876318]])

In [79]:
hiDDen=np.apply_along_axis(sigFunc,1,mult_data)

In [80]:
np.linalg.pinv(hiDDen)

array([[ 114.52618125, -116.58005697],
       [-115.76207588,  119.40364117]])

In [82]:
from scipy.linalg import pinv2 as scip_pinv
scip_pinv(hiDDen)

array([[ 114.52618125, -116.58005697],
       [-115.76207588,  119.40364117]])

In [1]:


class ELM_MultiLabel:
    def __init__(self, input_nodes, hidden_nodes, output_nodes, activation, bias=True, random_gen="uniform"):
        """
        Args:
            input_nodes ([integer]): Number of Input nodes
            hidden_nodes ([integer]): Number of hidden nodes
            output_nodes ([integer]): Number of output nodes
            activation ([function]): The function which will be used as the activation function in the hidden layer
            bias ([boolean]): Flag to use bias, if True then randomly generate bias @random_gen else bias - 0.
            random_gen (str, optional): The type way in which random weight are generated. Defaults to "uniform".
        """
        self.__input_nodes = input_nodes
        self.__hidden_nodes = hidden_nodes
        self.__output_nodes = output_nodes
        if random_gen == "uniform":
            self.__beta = np.random.uniform(-1.,1.,size = (self.__hidden_nodes, self.__output_nodes))
            self.__alpha = np.random.uniform(-1.,1.,size = (self.__input_nodes, self.__hidden_nodes))
            self.__bias = np.random.uniform(size = (self.__hidden_nodes,))
        else:
            self.__beta = np.random.normal(-1.,1.,size=(self.__hidden_nodes, self.__output_nodes))
            self.__alpha = np.random.normal(-1.,1.,size=(self.__input_nodes, self.__hidden_nodes))
            self.__bias = np.random.normal(size=(self.__n_hidden_nodes,)) 
        self.__activation = activation # Sigmoid Function

    def getInputNodes(self):
        return  self.__input_nodes

    def getHiddenNodes(self):
        return  self.__hidden_nodes

    def getOutputNodes(self):
        return  self.__output_nodes
    
    def getBetaWeights(self):
        return self.__beta
    
    def getAlphaWeight(self):
        return self.__alphs
    
    def getBias(self):
        return self.__bias

    def __get_H_matrix(self, train_x, verbose=False):
        # 1 Propagate data from Input to hidden Layer
        if verbose:
            print("Propagate data from Input to hidden Layer")
        inp = np.dot(train_x , self.__alpha)
        if verbose:
            print(inp)
            print("Adding Biases")
        inp = inp  + self.__bias
        if verbose:
            print(inp)
            print("Applyin activation function")
        inp_activation = np.apply_along_axis(self.__activation, 1, inp)
        return inp_activation

    def fit(self, train_x, train_y, verbose = False, show_metrics = True):
        """
        This function calculates the Beta weights or the output weights
        train_x : input matrix
        train_y : output matrix to be predicted or learned upon unipolar

        """
        if verbose:
            print("train_x shape:", train_x.shape)
            print("train_y shape:", train_y.shape)
        inp_activation = self.__get_H_matrix(train_x, verbose)
        # This is the H matrix getting its Moore Penrose Inverse
        if verbose:
            print(inp_activation)
            print("Getting the Generalized Moore Penrose Inverse")
        generalizedInverse = np.linalg.pinv(inp_activation)
        if verbose:
            print(generalizedInverse)
            print("Finding Beta, output weights")
        # Now find output weight matrix Beta 
        # convert input Y values according to the threshold using biploar step function
        predicted_bipolar=  np.apply_along_axis(_biploar_step, 1, train_y)
        self.__beta = np.dot(generalizedInverse, predicted_bipolar)
        if verbose:
            print("Beta Matrix Weights")
            print(self.__beta)

        if(show_metrics):
            print("Model Metrics, for Training :")
            self.predict(train_x, train_y,verbose,show_metrics)
    
    def predict(self, test_x, test_y = None, verbose = False, show_metrics= True):
        """
        preditcts the output for the input test data
        call this after calling the fit.
        test_data shape should be (batch_size,768 or input_nodes)
        output_shape will be (batch_size, 71 or output_nodes)

        returns: Predicted Label Matrix
        """
        if verbose:
            print("Predicting outputs")
        inp_activation = self.__get_H_matrix(test_x, verbose)
        output_predicted = np.dot(inp_activation, self.__beta)
        # convert predicted according to the threshold using biploar step function
        predicted_bipolar =  np.apply_along_axis(_biploar_step, 1, output_predicted)
        predicted_binary = np.apply_along_axis(_binary_step, 1, predicted_bipolar)

        if verbose:
            print("predicted output")
            print(output_predicted)
            print("predicted_bipolar")
            print(predicted_bipolar)
            print("predicted_binary")
            print(predicted_binary)
            print("Original Binary")
            print(test_y)

        if(test_y is not None):
            self.__evaluate(test_y,predicted_binary)
        return predicted_binary

    def __evaluate(self, real, predicted):
        """
        real values as 0,1
        predicted values as 0,1
        """
        # Now we find accuracy, precision, recall, Hamming Loss and F1 Measure
        accuracy = accuracy_score(real, predicted)
        hamLoss = hamming_loss(real, predicted)
        # element wise correctness
        term_wise_accuracy=np.sum(np.logical_not(np.logical_xor(real, predicted)))/real.size

        macro_precision = precision_score(real, predicted, average='macro')
        macro_recall = recall_score(real, predicted, average='macro')
        macro_f1 = f1_score(real, predicted, average='macro')

        micro_precision = precision_score(real, predicted, average='micro')
        micro_recall = recall_score(real, predicted, average='micro')
        micro_f1 = f1_score(real, predicted, average='micro')
        
        metricTable=prettytable.PrettyTable()
        metricTable.field_names = ["Metric", "Macro Value", "Micro Value"]
        metricTable.add_row(["Hamming Loss","{0:.3f}".format(hamLoss) ,""])
        metricTable.add_row(["Term Wise Accuracy","{0:.3f}".format(term_wise_accuracy) ,""])

        metricTable.add_row(["Accuracy","{0:.3f}".format(accuracy),""])
        metricTable.add_row(["Precision","{0:.3f}".format(macro_precision),"{0:.3f}".format(micro_precision)])
        metricTable.add_row(["Recall","{0:.3f}".format(macro_recall),"{0:.3f}".format(micro_recall)])
        metricTable.add_row(["F1-measure","{0:.3f}".format(macro_f1),"{0:.3f}".format(micro_f1)])

        print(metricTable)

        print("Metrics @ Literature")
        self.get_eval_metrics(real,predicted)

        print("Classification Report")
        print(classification_report(real,predicted))

    def get_eval_metrics(self, real, predicted, verbose= False):
        err_cnt_accuracy=0
        err_cnt_precision=0
        err_cnt_recall=0
        if verbose:
            print(real)
            print(predicted)
        for x in range(real.shape[0]):
            err_and= np.logical_and(real[x],predicted[x])
            err_or = np.logical_or(real[x],predicted[x])
            # Accuracy
            err_cnt_accuracy +=(sum(err_and)/sum(err_or))

            # Precision
            if sum(err_and) != 0:
                err_cnt_precision += (sum(err_and) / sum(predicted[x]))
            # Recall
            err_cnt_recall += (sum(err_and) / sum(real[x]))
            if verbose:
                print("Iteration :",x)
                print((sum(err_and)/sum(err_or)))
                print(err_and)
                print(err_or)
                print(err_cnt)
        
        err_count_hamming = np.zeros((a.shape))

        for i in range(real.shape[0]):
            for j in range(real.shape[1]):
                if real[i,j] != predicted[i,j]:
                    err_count_hamming[1,j] = err_count_hamming[1,j]+1

        sum_err = np.sum(err_count_hamming);
        HammingLoss = sum_err/real.size;
        accuracy = err_cnt_accuracy / a.shape[1]
        precision = err_cnt_precision / a.shape[1]
        recall = err_cnt_recall / a.shape[1]
        f1 = 2*((precision*recall)/(precision+recall))
        print("Final: ")
        print("Hamming Loss: ", HammingLoss)
        print("Accuracy: ",accuracy)
        print("precision: ",precision)
        print("recall: ",recall)
        print("f1: ",f1)

        metricTable=prettytable.PrettyTable()
        metricTable.field_names = ["Metric", "Value"]
        metricTable.add_row([" Literature Hamming Loss","{0:.3f}".format(HammingLoss)])
        metricTable.add_row(["Literature Accuracy","{0:.3f}".format(accuracy)])

        metricTable.add_row(["Literature Precision","{0:.3f}".format(precision)])
        metricTable.add_row(["LiteratureRecall","{0:.3f}".format(recall)])
        metricTable.add_row(["LiteratureF1-measure","{0:.3f}".format(f1)])

        print(metricTable)


In [4]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, multilabel_confusion_matrix, hamming_loss,classification_report

_bipolar_sigmoid=np.vectorize(lambda x: (1. - np.exp(-x))/(1. + np.exp(-x)))


In [6]:
t1_emlMLTC_500= ELM_MultiLabel(input_nodes=768, hidden_nodes=500, output_nodes=71, activation=_bipolar_sigmoid)
print("Training Model with 500 hidden nodes")
#t1_emlMLTC_500.fit(type1_BERT_Embeddings_Train,label_values_Train, verbose=False, show_metrics=True)

Training Model with 500 hidden nodes


In [9]:
import pickle


ModuleNotFoundError: No module named 'dill'

In [8]:
filename = 'ELM_500t1_bipolarstep.sav'
pickle.dump(t1_emlMLTC_500, open(filename, 'wb'))

PicklingError: Can't pickle <function <lambda> at 0x0000018BAFFA8EE8>: attribute lookup <lambda> on __main__ failed

In [10]:
import json

In [11]:
json.dumps(t1_emlMLTC_500)

TypeError: Object of type ELM_MultiLabel is not JSON serializable